### ISSUE TITLE
MailPoet compatibility issue

### ISSUE THREAD

**Issue by costasovo** [Bit-Apps-Pro/bit-integrations#27]
I am a developer for the MailPoet WordPress plugin, and I wanted to bring an important update regarding the use of our internal code to your attention.

We have noticed that your project is utilizing code within the \MailPoet\Models namespace. This code has been deprecated for some time and has been triggering warnings. It was not intended for external use. We have always provided a [public API](https://github.com/mailpoet/mailpoet/tree/trunk/doc).

We have prepared a [pull request](https://github.com/mailpoet/mailpoet/pull/5734) to remove this obsolete code entirely. This change is necessary to maintain MailPoet's integrity and performance. The pull request is ready and will be merged soon.

To avoid disruptions, please update your project to stop using the \MailPoet\Models namespace code instead of relying on our provided [public API](https://github.com/mailpoet/mailpoet/tree/trunk/doc). If this update is not made, your code will fail once the pull request is merged and the new version is released. We aim to release it within the next couple of weeks.

Thank you for your understanding and cooperation.

**Comment by RishadAlam** [comment]
Dear @costasovo 

Thank you for reaching out and informing us about the upcoming changes to the MailPoet plugin. We appreciate the heads-up and the proactive steps you’ve taken to maintain the integrity and performance of MailPoet.

We have reviewed your notice and have updated our project accordingly. We have replaced our use of the \MailPoet\Models namespace with the recommended MailPoet public API. We understand the importance of this update and have made the necessary changes to ensure our code remains compatible with future versions of MailPoet.

Changelog
	Removed: All instances of deprecated \MailPoet\Models code.
	Updated: Replaced deprecated code with the MailPoet public API.

We appreciate your cooperation and support. If there are any further changes or updates we should be aware of, please let us know.

Thank you for your understanding and assistance.
